### PR TITLE
add an array to loop through command

### PR DESCRIPTION
**Pull request by CloudBeard**
Created a way to allow for multiple targets to be passed into the oscal-target to let Lula Lint multiple files without updating actual Lula/Go-OSCAL codebase.

### CODE REVIEW

**Comment by brandtkeller** [comment]
Dropping discussed comment here for posterity:

High level looks good - I’d like understand:

- Testing this and ensuring exit codes are honored
- How you intend to collect the file paths
- Potentially how best to format the inputs - One long string is less desirable than say  a json object with the action supporting fromJson()

**Comment by CloudBeard** [comment]
As apart of the action that calls the lula-action I was thinking something like

```yaml
      - name: Get modified OSCAL files
        id: get-modified-files
        uses: actions/github-script@v7
        with:
          script: |
            const pattern = '**/*oscal-component.yaml';
            const { data } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const changedFiles = data.filter(file => file.filename.match(pattern)).map(file => file.filename);
            return changedFiles.join(' ');
          result-encoding: string

```

Tried testing locally with ACT but ran into some issues checking for changes without github token. May have to look into setting up a whole repo for testing.

**Comment by CloudBeard** [comment]
I had to modify my const pattern above.

First test with 2 valid oscal files.

image


Second test with 1 valid 1 invalid
Results: It does fail correctly and does give the error output. Noticed it didn't touch the second OSCAL file, exits on first failure
image

Third test with 2 invalid
Result: It does fail correctly but exits on first lint failure.
image

Going to test if I can allow linting of all files but still fail if one fails so you can see multiple failures vs multiples runs to see that.

**Comment by CloudBeard** [comment]
Tested new Action logic to handle Lula exit code.
Result:  Does show all errors, tried removing various pieces to see all of the errors. One piece was trunicated in the GitHub log compared to running locally but still leaves enough to find the error.

image

**Comment by CloudBeard** [comment]
This is the workflow code used

```yaml
name: lula-lint

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*oscal-component.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        # with:
        #   ref: ${{ github.head_ref }}

      - name: Get modified OSCAL files
        id: get-modified-files
        uses: actions/github-script@v7
        with:
          script: |
            const pattern = /.+oscal-component\.yaml$/;
            const { data } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const changedFiles = data.filter(file => file.filename.match(pattern)).map(file => file.filename);
            return changedFiles.join(' ');
          result-encoding: string

      # Runs the Lula Setup Action
      - name: Lula Setup
        uses: ./.github/actions/lula-setup

      # Runs Lula Lint
      - name: Lula Lint DUBBD
        uses: ./.github/actions/lula-lint
        with:
          oscal-target: ${{ steps.get-modified-files.outputs.result }}
```

Haven't tried with fromJson() yet since this was quick to test (minus setting up the test repo but needed either way).

**Comment by brandtkeller** [comment]
I need to provide more context around E2E vision - but with the current state of composing component-definitions we may find ourselves using OSCAL to orchestrate many component-definitions rather than lula/lula-action independently. 

Don't close this out just yet - but wanted to provide that so that we can assess if this is still a requirement.

**Comment by CloudBeard** [comment]
Functionality is native to lula

**Pull request closed without merging**
